# Generated by Django 5.2.8 on 2025-11-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_notification'),
    ]

    def update_pending_to_active(apps, schema_editor):
        """Update all PENDING tasks to ACTIVE"""
        Todo = apps.get_model('todo_app', 'Todo')
        Todo.objects.filter(status='PENDING').update(status='ACTIVE')

    operations = [
        # First, update existing PENDING records to ACTIVE
        migrations.RunPython(update_pending_to_active, reverse_code=migrations.RunPython.noop),
        # Then, alter the field to remove PENDING from choices
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
    ]
